tutorcruncher/hermes

.gitignore
app/base_schema.py
app/callbooker/_availability.py
app/callbooker/_process.py
app/callbooker/_schema.py
app/callbooker/views.py
app/main.py
app/tc2/_process.py
tests/test_callbooker.py
tests/test_tc2.py

- Calls cannot be booked on weekends
- Assume that every time a support call happens, the cligency exists
- Adding CORS policy when not in dev mode
- No longer ignoring client callbacks in some circumstances

Changes made while testing on the website

---

README.md
app/callbooker/views.py
app/pipedrive/_schema.py
app/pipedrive/api.py
app/pipedrive/views.py
app/tc2/_process.py
app/tc2/_schema.py
app/utils.py
tests/test_pipedrive.py
tests/test_tc2.py

Not only were we posting to pipedrive with primary_email, which was broken
we also were not retrieving the email and phone number correctly from tc2

Pipedrive person Email Fix

---

app/admin/resources.py
app/base_schema.py
app/callbooker/_schema.py
app/main.py
app/models.py
app/pipedrive/_process.py
app/pipedrive/_schema.py
app/pipedrive/tasks.py
app/settings.py
app/tc2/_process.py
app/tc2/_schema.py
app/tc2/tasks.py
tests/conftest.py
tests/test_combined.py
tests/test_pipedrive.py
tests/test_tc2.py

Look at the CustomField model for an explanation on how custom fields now work.
TODO: Do migs.

Custom fields V2

---

app/main.py
migrations/models/0_20231115143509_init.py
pyproject.toml
requirements.txt

- Optimise changes made whilst THS was away
- Fix tests
- Changing to Rediscloud
- Move to pydantic v2
- Upgrading to Pydantic2
- Finish Pydantic2
- Fix database url
- Add aerich for migrations

Use aerich for migrations

---

app/tc2/_schema.py
tests/test_tc2.py

Fix price plan validator, to set `1-basic` to `payg`

---

app/callbooker/_process.py
tests/test_callbooker.py

Fix #111﻿
get or create Contact,
if it can get a contact, but the contact has no email. Update it

if Contact exists but doesnt have an email update

---

app/admin/templates/base.html

added
```
<meta name="robots" content="noindex, nofollow">
```

no index no follow

---

app/tc2/views.py
tests/test_tc2.py

Fix #96
Created `IGNORED_ACTIONS`﻿:
- 'CLIENT_ENQUIRY'
- 'AGREED_TERMS'
in tc2 callback if event.action is in IGNORED_ACTIONS we skip it.

Ignore Some Actions

---

app/tc2/_schema.py
tests/test_tc2.py

Reverts tutorcruncher/hermes#145

Revert "make TCUser email optional"

---

app/tc2/_schema.py
tests/test_tc2.py

Reverts tutorcruncher/hermes#149

Revert "Revert "make TCUser email optional""

---

app/base_schema.py
app/callbooker/_schema.py
app/pipedrive/_schema.py
tests/test_combined.py

had to modify the get_custom_field_vals to return the getattr from the hermes_fieldname + _id except if the hermes_field_name was id ---> meaning it was a hermes id custom field, and had to be takedn from the hermes_field_name

If hermes_field_name + _id is none set cf.value to none

---

README.md
app/pipedrive/api.py
app/tc2/_process.py

Ensure that each function has a docstring﻿

Ensure everything has a docstring

---

app/main.py

Close #176 
Aim is to get http response error to be reported in Sentry﻿

More sentry reporting

---

app/main.py
pyproject.toml
requirements.txt

- update logfire
- fix ruff lint

Update Logfire to latest

---

patch.py
requirements.txt

Close #258
get all Companies with a price_plan
post object to pd to update the Org
- setup
- create new data field for `price_plan`﻿
- create new custom field for `price_plan`
- run patch
- see Org now has new populated field

Add patch to update PD Org price_plans

---

app/models.py
app/pipedrive/_process.py
migrations/models/6_20240902131205_update_customfieldvalue_max_length.py
migrations/models/7_20240902131205_update_customfieldvalue_null.py
tests/test_combined.py

create migration to change CustomFieldValue.value max_length form 255 to 10000
also allow customFieldValue to be null

adjust custom field value max_length and allow null

---

app/pipedrive/_process.py
app/pipedrive/_schema.py
app/pipedrive/api.py
app/pipedrive/tasks.py
tests/test_combined.py
tests/test_pipedrive.py

- fixed duplicate ids
- create test

Fix handling of duplicate hermes ids, also catch update pd deal error deal not found

---

app/pipedrive/_process.py
tests/test_combined.py

Commenting out logic to update the inherited custom fields on deals, on the process pd org Pipedrive webhook

comment out inherited cfs

---

app/pipedrive/views.py
tests/test_combined.py
tests/test_pipedrive.py

Was always being called, causing items to be uneditable

temp remove handle duplicate ids

---

app/callbooker/_booking.py
app/callbooker/_meeting_content_templates.py
migrations/models/7_20240902131205_update_customfieldvalue_null.py
patch.py

Close #247
Close #261
added more vars to the MEETING.TYPE_SALES
company name
email
phone
estimated montly income
country
also pass the pipedrive url if the pd_org_id exists
before
after
Inorder to property test this, we would need to create a more accurate mock of the gcal

Improve the 'Admin' data at bottom of calendar meeting template

---

app/callbooker/_availability.py
tests/test_callbooker.py

Fix #295 where the slot is the exact same time as the demo
